on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          chmod a+x ./ci/check.sh
          ./ci/check.sh
