on: workflow_dispatch

name: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: publish
      deployment: false
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          chmod a+x ./ci/publish.sh
          ./ci/publish.sh
